Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HiddenCurrency2__c</fullName>
        <label>HiddenCurrency2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HiddenCurrency__c</fullName>
        <label>HiddenCurrency</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HiddenPercent__c</fullName>
        <label>HiddenPercent</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Assignment/classes/getContactController.cls
public class getContactController{
    @AuraEnabled
    public static wrapperClass getCases(Id key){
        
        wrapperClass returnwrapperClass = new wrapperClass();
        
        returnwrapperClass.lstContact = [SELECT Id, Subject, Type, ContactId, Contact.Product__c, Contact.Home_Country__c FROM case where id=:key];
        
        for(Case caseloop : returnwrapperClass.lstContact )
        {
            string key2 = string.valueof(caseloop.ContactId);
            returnwrapperClass.lstCon = [Select Product__c, Home_Country__c, HiddenCurrency__c, HiddenCurrency2__c, HiddenPercent__c from Contact where id=:key2];    
        }
        return returnwrapperClass;
    }
    
    public class wrapperClass{
        @AuraEnabled public List<Case> lstContact{get;set;}
        @AuraEnabled public List<Contact> lstCon{get;set;}

    }
}