Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                    <default>true</default>
                    <label>en</label>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <description>This field is to store Survey Date</description>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

Assignment/classes/Contact_batchSurveyToUser_Test.cls
@isTest

public class Contact_batchSurveyToUser_Test{

    static testMethod void testbatch(){
    
    List<Contact> lstCon = new List<Contact>();
    for(Integer i=0; i < 10; i++){
    
        Contact con = new Contact();
        con.FirstName ='Test';
        con.LastName  ='Name'+i;
        con.Language__c = 'de';
        con.survey_date__c = System.today() - 2;
        lstCon.add(con);
    }
    insert lstCon;
    
    test.startTest();
    
    Contact_batchSurveyToUser obj = new Contact_batchSurveyToUser();
    Database.executebatch(obj);
    
    test.stopTest();
    
    
    }

}